import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar";
import HideNavbar from "./hide-navbar";
import BootstrapClient from "./bootstrap-client";
import SiteSettingsClientEffect from "@/components/site-settings-client-effect";
import Footer from "@/components/footer";
import "./custom-bootstrap.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} d-flex flex-column min-vh-100`}>
        <SiteSettingsClientEffect />
        <BootstrapClient />
        <HideNavbar>
          <Navbar />
        </HideNavbar>
        <div className="flex-grow-1">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
